---
- hosts: "{{ project }}_SERVICES"
  serial: 1
  max_fail_percentage: 0
  tasks:
    - include: tasks/stopvm.yaml
- hosts: "{{ project }}"
  serial: 1
  max_fail_percentage: 0
  tasks:
    - include: tasks/stopvm.yaml
