---

- hosts: "{{ project }}"
  connection: local
  serial: 2
  max_fail_percentage: 10
  tasks:
    - include: tasks/startvm.yaml
# Pause for 2 minutes to let storage and infrastructure services come up
- pause: minutes=2
- hosts: "{{ project }}_SERVICES"
  connection: local
  serial: 2
  max_fail_percentage: 10
  tasks:
    - include: tasks/startvm.yaml
